(function(){'use strict';
var CSS=`
html,body{max-width:100%;overflow-x:hidden!important}*,*:before,*:after{box-sizing:border-box}img,svg,video,canvas{max-width:100%;height:auto}button,input,select,textarea{max-width:100%;font:inherit}.maxw{width:calc(100% - 48px);max-width:1280px;padding:0;margin-inline:auto}h1{font-size:clamp(2rem,5vw,3.5rem);line-height:1.1;overflow-wrap:anywhere}h2{font-size:clamp(1.6rem,3.2vw,2.25rem);line-height:1.18;overflow-wrap:anywhere}.btn{min-height:44px;max-width:100%;justify-content:center}:focus-visible{outline:2px solid #2E7DA8;outline-offset:3px}
.beup-mobile-toggle{display:none;appearance:none;border:0;background:transparent;color:inherit;width:44px;height:44px;padding:9px;cursor:pointer;align-items:center;justify-content:center;flex-direction:column;gap:5px}.beup-mobile-toggle span{display:block;width:24px;height:2px;background:currentColor;border-radius:2px;transition:.25s}.beup-mobile-toggle[aria-expanded=true] span:nth-child(1){transform:translateY(7px) rotate(45deg)}.beup-mobile-toggle[aria-expanded=true] span:nth-child(2){opacity:0}.beup-mobile-toggle[aria-expanded=true] span:nth-child(3){transform:translateY(-7px) rotate(-45deg)}.beup-mobile-menu{position:fixed;inset:64px 0 auto;z-index:10000;background:#fff;border-top:1px solid rgba(11,31,58,.12);box-shadow:0 18px 40px rgba(11,31,58,.12);padding:12px 24px 24px;display:grid;gap:0;opacity:0;visibility:hidden;transform:translateY(-10px);transition:.25s;max-height:calc(100vh - 64px);overflow:auto}.beup-mobile-menu.is-open{opacity:1;visibility:visible;transform:none}.beup-mobile-menu a{display:flex;align-items:center;min-height:48px;padding:10px 4px;font-size:15px;font-weight:600;border-bottom:1px solid rgba(11,31,58,.12);color:#0B1F3A;text-decoration:none}body.beup-menu-open{overflow:hidden}
.featured-visual{min-height:0!important;height:auto!important;padding:28px!important}.featured-visual svg{width:min(100%,220px);height:auto}
@media(max-width:1023px){.maxw{width:calc(100% - 48px)}header{position:sticky!important;top:0;z-index:900;padding:10px 0!important;background:#fff!important;box-shadow:0 1px 0 rgba(11,31,58,.12)}header .maxw{min-height:64px;display:flex;align-items:center;justify-content:space-between}header nav,header .btn{display:none!important}.beup-mobile-toggle{display:flex}.hero .maxw,.challenge .maxw,.integrated .maxw,.why .maxw,.why-exist .maxw,.challenges .maxw,.solutions .maxw,.contact-grid{grid-template-columns:1fr}.svc-row{grid-template-columns:64px minmax(0,1fr);}.svc-row .rcopy{grid-column:2}.aud-grid,.article-grid,.industries-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.principle-grid,.outcome-grid,.related-grid,.team-grid,.value-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.featured-card{grid-template-columns:1fr}.featured-body{padding:28px}.hero-visual{height:260px}.footer-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:767px){.maxw{width:calc(100% - 32px)}section{padding-block:48px 64px}.hero{padding-top:104px;padding-bottom:56px}.hero-ctas,.final-cta .ctas,.ind-hero .ctas,.article-cta .ctas,.confirm-card .ctas{display:grid;grid-template-columns:1fr;gap:10px}.hero-ctas .btn,.final-cta .btn,.ind-hero .btn,.article-cta .btn,.confirm-card .btn{width:100%}.hero-visual{height:220px}.aud-grid,.article-grid,.industries-grid,.principle-grid,.outcome-grid,.related-grid,.team-grid,.value-grid{grid-template-columns:1fr}.svc-row{grid-template-columns:1fr}.svc-row .rcopy{grid-column:auto}.footer-grid{grid-template-columns:1fr}.footer-bottom{display:grid;gap:10px}.narrow{width:calc(100% - 32px);padding:0}.article-body{font-size:16px}.engage-track{grid-template-columns:1fr!important}.time-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:374px){.time-grid{grid-template-columns:1fr}.btn{padding-inline:16px}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important}}
`;
function fix(doc){if(!doc||doc.getElementById('beup-frame-fixes'))return;var st=doc.createElement('style');st.id='beup-frame-fixes';st.textContent=CSS;doc.head.appendChild(st);var header=doc.querySelector('header'),nav=header&&header.querySelector('nav');if(!header||!nav)return;var max=header.querySelector('.maxw')||header,t=doc.createElement('button');t.className='beup-mobile-toggle';t.type='button';t.setAttribute('aria-label','Open menu');t.setAttribute('aria-expanded','false');t.innerHTML='<span></span><span></span><span></span>';max.appendChild(t);var m=doc.createElement('div');m.id='beup-mobile-menu';m.className='beup-mobile-menu';m.setAttribute('aria-hidden','true');var items=[['/','Home'],['/about','About'],['/approach','Our Approach'],['/services','Services'],['/industries','Industries'],['/insights','Insights'],['/contact','Contact'],['/business-growth-checkup','Business Growth Checkup'],['/book-consultation','Book a Consultation']];m.innerHTML=items.map(function(x){return '<a href="'+x[0]+'">'+x[1]+'</a>'}).join('');doc.body.appendChild(m);function close(){t.setAttribute('aria-expanded','false');t.setAttribute('aria-label','Open menu');m.classList.remove('is-open');m.setAttribute('aria-hidden','true');doc.body.classList.remove('beup-menu-open')}function open(){t.setAttribute('aria-expanded','true');t.setAttribute('aria-label','Close menu');m.classList.add('is-open');m.setAttribute('aria-hidden','false');doc.body.classList.add('beup-menu-open')}t.addEventListener('click',function(){t.getAttribute('aria-expanded')==='true'?close():open()});m.querySelectorAll('a').forEach(function(a){a.addEventListener('click',close)});doc.addEventListener('keydown',function(e){if(e.key==='Escape')close()});}
function watch(){var f=document.getElementById('page-frame');if(!f)return;f.addEventListener('load',function(){try{fix(f.contentDocument)}catch(e){}});try{if(f.contentDocument)fix(f.contentDocument)}catch(e){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();})();
